# Generated by Django 3.0.8 on 2021-04-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='college_part/college')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('computer_seats', models.IntegerField()),
                ('computer_cutoff', models.IntegerField()),
                ('IT_seats', models.IntegerField()),
                ('IT_cutoff', models.IntegerField()),
                ('civil_seats', models.IntegerField()),
                ('civil_cutoff', models.IntegerField()),
                ('mechanical_seats', models.IntegerField()),
                ('mechanical_cutoff', models.IntegerField()),
                ('electrical_seats', models.IntegerField()),
                ('electrical_cutoff', models.IntegerField()),
            ],
        ),
    ]
