# Generated by Django 3.0.8 on 2021-04-24 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Merit_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merit_score', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='college_part/student')),
                ('phone', models.IntegerField()),
                ('school', models.CharField(max_length=100)),
                ('physics_mark', models.IntegerField()),
                ('chemistry_mark', models.IntegerField()),
                ('maths_mark', models.IntegerField()),
                ('gcet_jee_mark', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
