# Generated by Django 3.0.8 on 2021-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_part', '0002_student_info_student_merit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='IT_cutoff',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='civil_cutoff',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='computer_cutoff',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='electrical_cutoff',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='mechanical_cutoff',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='chemistry_mark',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='gcet_jee_mark',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='maths_mark',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='physics_mark',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student_merit_score',
            name='merit_score',
            field=models.FloatField(),
        ),
    ]
