# Generated by Django 3.0.8 on 2021-04-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_part', '0003_auto_20210424_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='qoute',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
