# Generated by Django 3.0.8 on 2021-04-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_part', '0004_auto_20210426_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='qoute',
            field=models.CharField(max_length=255),
        ),
    ]
